module.exports = (sequelize,DataTypes)=>(
    sequelize.define('restaurant',{
        business_name:{
            type:DataTypes.STRING(30),
            allowNull:false,
            unique:true,
        },
        tel:{
            type:DataTypes.STRING(40),
            allowNull:false,
            unique:true,
        },
        restaurant_type:{
            type:DataTypes.STRING(20),
            allowNull:false,
        },
        address:{
            type:DataTypes.STRING(100),
            allowNull:false,
        },
        owner:{
            type:DataTypes.STRING(10),
            allowNull:false,
        },
        open_time:{
            type:DataTypes.STRING(40),
            allowNull:false,
        },
        close_time:{
            type:DataTypes.STRING(40),
            allowNull:false,
        }
    })
);